name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi:x86_64-zephyr-elf

      - name: Build
        run: |
          west build -p always -b native_sim app

      - name: Twister
        working-directory: app
        shell: bash
        run: |
          west twister -p native_sim -T app/tests/ -v --inline-logs --integration
    